export const services=[
 {title:'Website Development & Web Design',problem:'Your online presence does not look premium enough for serious customers.',solution:'Cinematic Next.js websites with strong copy, service sections, pricing, FAQ, trust signals, and fast mobile UX.',outcome:'Higher trust, stronger first impression, and more qualified inquiries.'},
 {title:'AI Automation Services',problem:'You get inquiries but follow-up is slow, scattered, or completely manual.',solution:'Lead forms, Supabase CRM, instant admin emails, client confirmation emails, and status tracking.',outcome:'Faster response time and a cleaner sales pipeline.'},
 {title:'CRM & Content Systems',problem:'Your visuals, text, colors, and social presence do not feel consistent.',solution:'Premium content structure, case-study layouts, CRM-ready lead capture, brand direction, and manageable content blocks.',outcome:'Your business looks established and organized before the first call.'},
 {title:'Digital Growth & SEO Support',problem:'After launch, websites become outdated and no one improves conversion.',solution:'Monthly updates, blog publishing, SEO checks, new sections, analytics review, and UI improvements.',outcome:'Your website keeps growing with the business.'}
];
export const stats=['24h Response','AI-Powered Workflows','Nagpur Based','Fast Delivery'];
export const faqs=[
 ['How fast can you deliver?','Most premium starter websites can be delivered in 7–14 days after content confirmation. Larger systems with dashboards and automation can take longer depending on scope.'],
 ['Do you make only frontend?','No. We build full systems: frontend, backend, database, lead capture, email notifications, admin dashboards, and content management.'],
 ['Can you redesign my existing website?','Yes. We can audit, redesign, and rebuild your website into a premium conversion-focused system with better copy, speed, UX, and lead flow.'],
 ['Will I be able to update content myself?','Yes. The admin dashboard can manage leads, blogs, portfolio projects, testimonials, pricing, newsletter subscribers, and site settings.'],
 ['Do you provide support after launch?','Yes. Monthly maintenance and growth support are available for updates, SEO improvements, content, bug fixes, and new features.'],
 ['Can you connect domain, email, and deployment?','Yes. We can guide setup for Vercel, Namecheap/DNS, Supabase, Clerk, Resend, and production environment variables.'],
 ['Do you provide AI automation and website development in Nagpur?','Yes. NexusNova Studio is based in Nagpur, Maharashtra and works with local businesses and growing companies across India on websites, CRM systems, and automation workflows.']
];
export const demoProjects=[
 {title:'Restaurant Growth Website',industry:'Restaurant',summary:'A warm luxury website with menu highlights, WhatsApp ordering, gallery, local SEO, and lead tracking.',results:'+35% estimated inquiry lift'},
 {title:'Clinic Appointment Funnel',industry:'Healthcare',summary:'Trust-first clinic website with doctor profile, services, appointment form, patient FAQs, and automated email alerts.',results:'Faster appointment capture'},
 {title:'Real Estate Lead Engine',industry:'Real Estate',summary:'Premium landing system for builders with project gallery, brochure CTA, amenities, location, and inquiry pipeline.',results:'Higher quality buyer leads'},
 {title:'Salon Booking Experience',industry:'Beauty',summary:'Elegant booking-focused website with service menu, offers, Instagram-style gallery, and WhatsApp call-to-action.',results:'More service bookings'},
 {title:'Coaching Institute Funnel',industry:'Education',summary:'Course landing pages with result proof, batches, fees, demo class CTA, and student inquiry tracking.',results:'Better admission inquiries'},
 {title:'Local Business Automation',industry:'Services',summary:'Lead capture system with email alerts, CRM statuses, newsletter collection, and admin-managed site content.',results:'Cleaner follow-up workflow'}
];
export const demoPosts=[
 {id:'demo-1',slug:'premium-website-checklist',title:'Premium Website Checklist for Local Businesses',excerpt:'The sections, CTAs, trust blocks, and backend systems your business website should include.',content:'A high-performing business website starts with a clear service promise, fast mobile design, credible proof, and one obvious contact action.\n\nFor local businesses in Nagpur and across India, add accurate location and contact information, meaningful service descriptions, customer questions, and case studies. Make every key page quick to scan and easy to act on.\n\nBehind the design, connect inquiry forms to reliable notifications and a manageable pipeline. Premium design earns attention; consistent follow-up turns that attention into leads.'},
 {id:'demo-2',slug:'ai-automation-for-small-business',title:'How AI Automation Helps Small Businesses Respond Faster',excerpt:'A simple guide to lead forms, confirmation emails, CRM statuses, and WhatsApp follow-up.',content:'AI automation services are most useful when they remove delay from real business workflows. A structured inquiry form can route leads, send confirmation emails, and organize follow-up details the moment a potential customer reaches out.\n\nFor growing businesses, simple CRM development and business automation can improve response consistency without making the experience impersonal. Teams keep control while routine work becomes faster.\n\nStart with one measurable workflow, such as new lead follow-up or appointment requests, then expand only after it delivers value.'},
 {id:'demo-3',slug:'why-branding-improves-conversion',title:'Why Better Branding Improves Website Conversion',excerpt:'Premium colors, typography, spacing, and case-study layouts make customers trust you faster.',content:'Visitors make decisions quickly. Clean typography, consistent visual identity, focused website copy, and well-organized proof help a company look credible before a conversation begins.\n\nA web design company should connect brand presentation with practical conversion paths: service pages, case studies, local relevance, accessible calls to action, and a contact experience that feels effortless.\n\nFor an AI agency or digital transformation partner, polished design also makes technical services easier to understand and trust.'}
];
export const pricing=[
 {name:'Launch',price:'₹14,999',desc:'For small businesses that need a premium online presence fast.',features:['5-page luxury website','Mobile responsive UX','Contact + WhatsApp leads','Basic SEO setup','Speed optimized sections','7-day delivery target']},
 {name:'Growth',price:'₹29,999',desc:'For businesses that need website + backend lead system.',popular:true,features:['Everything in Launch','Supabase lead database','Admin dashboard','Blog + portfolio management','Admin + client emails','Pricing/testimonials CRUD']},
 {name:'Scale',price:'Custom',desc:'For automation, SaaS, dashboards, and advanced workflows.',features:['AI workflow automation','Client portal options','Advanced dashboards','Razorpay/Stripe planning','Custom integrations','Monthly growth support']}
];
