import Link from 'next/link';
import { ArrowRight, Check, Sparkles, Zap, ShieldCheck, Bot, BarChart3, Smartphone, Palette, MessageCircle, Star, Workflow } from 'lucide-react';
import { demoProjects, faqs, pricing, services, stats } from '@/lib/data';
import { FloatingMockup, Reveal, TiltCard } from './motion';

type Project = { title: string; slug?: string; industry: string; summary: string; results?: string; image_url?: string };
type Plan = { name: string; price: string | number; desc?: string; description?: string; features: string[]; popular?: boolean };
type Testimonial = { name: string; role?: string; company?: string; quote: string; rating?: number };
function projectSlug(p: Project) { return p.slug || p.title.toLowerCase().replaceAll(' ', '-'); }

export function Hero() {
  return <section className="lux-bg noise relative overflow-hidden px-5 pb-28 pt-36 md:pt-44"><div className="grid-bg absolute inset-0 opacity-70"/><div className="orb left-10 top-20 h-72 w-72 bg-amber-300/30"/><div className="orb right-10 top-32 h-96 w-96 bg-rose-400/25"/><div className="relative mx-auto max-w-7xl text-center"><Reveal><div className="mx-auto mb-6 inline-flex items-center gap-2 rounded-full border border-amber-200/20 bg-amber-100/10 px-4 py-2 text-sm text-amber-100"><Sparkles size={16}/> Luxury digital systems for serious businesses</div><h1 className="mx-auto max-w-6xl text-gradient text-5xl font-black tracking-[-.05em] md:text-7xl lg:text-8xl">Premium Websites, AI Automations & Brand Systems That Convert.</h1><p className="mx-auto mt-7 max-w-3xl text-lg leading-8 text-amber-50/70 md:text-xl">NexusNova Studio builds cinematic websites with backend lead systems, admin dashboards, email automation, and content tools — so your business looks premium and works smarter.</p><div className="mt-10 flex flex-col justify-center gap-4 sm:flex-row"><Link className="btn-lux px-8 py-4" href="/contact">Book Free Strategy Call</Link><Link className="rounded-full border border-amber-200/15 bg-white/[.04] px-8 py-4 font-bold text-amber-50 transition hover:bg-white/10" href="#work">Explore Work <ArrowRight className="inline" size={17}/></Link></div></Reveal><FloatingMockup/><div className="mt-14 grid grid-cols-2 gap-3 md:grid-cols-4">{stats.map((s,i)=><Reveal delay={i*.05} key={s}><TiltCard className="glass rounded-3xl p-5 text-sm text-amber-50/75"><p className="text-2xl font-bold text-amber-200">{i===0?'24h':i===1?'AI':i===2?'NGP':'Fast'}</p><p className="mt-1">{s}</p></TiltCard></Reveal>)}</div></div></section>
}

export function ProblemSection(){const items=[['Weak first impression','Visitors judge your brand in seconds. We create premium visual hierarchy, proof blocks, and fast mobile layouts.'],['Leads are getting lost','Every inquiry should be saved, tracked, emailed, and followed up through a clean admin pipeline.'],['Website feels generic','Your site needs a strong offer, case studies, pricing clarity, and micro-interactions that feel high-end.']];return <section className="relative px-5 py-24"><div className="mx-auto max-w-7xl"><Reveal><p className="text-sm uppercase tracking-[.35em] text-rose-200">Problems we solve</p><h2 className="mt-4 max-w-4xl text-4xl font-black tracking-tight md:text-6xl">A premium website is not decoration. It is your online sales machine.</h2></Reveal><div className="mt-12 grid gap-5 md:grid-cols-3">{items.map(([t,d],i)=><Reveal delay={i*.06} key={t}><TiltCard className="glass-warm rounded-[2rem] p-7"><div className="mb-6 flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br from-amber-300 to-rose-400 text-[#160d20]"><Zap size={20}/></div><h3 className="text-2xl font-bold">{t}</h3><p className="mt-4 leading-7 text-amber-50/62">{d}</p></TiltCard></Reveal>)}</div></div></section>}

export function Industries(){const industries=['Restaurants & Cafes','Clinics & Doctors','Real Estate & Builders','Salons & Beauty','Coaching Classes','Local Service Businesses'];return <section className="px-5 py-24"><div className="mx-auto max-w-7xl"><Reveal><p className="text-sm uppercase tracking-[.35em] text-amber-200">Focused industries</p><h2 className="mt-4 max-w-4xl text-4xl font-black tracking-tight md:text-6xl">Designed for businesses that need inquiries, bookings, trust, and repeat clients.</h2><p className="mt-5 max-w-2xl text-amber-50/62">Each industry gets tailored pages, WhatsApp CTAs, testimonial blocks, offer sections, local SEO structure, and an admin panel for updating content.</p></Reveal><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{industries.map((x,i)=><Reveal delay={i*.04} key={x}><div className="card-3d glass rounded-3xl p-7"><p className="text-xl font-bold text-amber-100">{x}</p><p className="mt-3 text-amber-50/55">Landing pages, lead capture, portfolio visuals, appointment CTAs, and follow-up automation.</p></div></Reveal>)}</div></div></section>}

export function Services(){const icons=[Palette,Workflow,Bot,ShieldCheck];return <section id="services" className="px-5 py-24"><div className="mx-auto max-w-7xl"><Reveal><p className="text-sm uppercase tracking-[.35em] text-rose-200">Services</p><h2 className="mt-4 text-4xl font-black tracking-tight md:text-6xl">Four premium offers. Built to sell clearly.</h2></Reveal><div className="mt-12 grid gap-5 md:grid-cols-2">{services.map((s,i)=>{const Icon=icons[i%icons.length];return <Reveal delay={i*.05} key={s.title}><TiltCard className="group glass-warm rounded-[2rem] p-8"><div className="flex items-start justify-between gap-6"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-amber-300 via-rose-400 to-violet-500 text-[#120d1f]"><Icon size={24}/></div><span className="rounded-full border border-white/10 px-3 py-1 text-sm text-white/45">0{i+1}</span></div><h3 className="mt-7 text-3xl font-black">{s.title}</h3><div className="mt-6 space-y-3"><p className="text-amber-50/50"><b className="text-rose-200">Problem:</b> {s.problem}</p><p className="text-amber-50/65"><b className="text-amber-200">Solution:</b> {s.solution}</p><p className="text-emerald-200"><b>Outcome:</b> {s.outcome}</p></div></TiltCard></Reveal>})}</div></div></section>}

export function WebsiteAudit(){const points=['Brand clarity score','Mobile UX and spacing','CTA and conversion flow','Local SEO foundations','Lead automation opportunities','Trust and case-study proof'];return <section className="px-5 py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.9fr_1.1fr]"><Reveal><div className="sticky top-28"><p className="text-sm uppercase tracking-[.35em] text-cyan-200">Free audit funnel</p><h2 className="mt-4 text-4xl font-black tracking-tight md:text-6xl">Give clients a reason to contact you before they are ready to buy.</h2><p className="mt-5 text-amber-50/62">A website audit lead magnet helps business owners understand what is broken and positions NexusNova as the expert.</p><Link href="/contact" className="btn-lux mt-8 inline-flex px-7 py-4">Get Website Audit</Link></div></Reveal><div className="grid gap-4 sm:grid-cols-2">{points.map((p,i)=><Reveal delay={i*.04} key={p}><div className="glass rounded-3xl p-6"><p className="text-sm text-amber-200/70">Audit {String(i+1).padStart(2,'0')}</p><p className="mt-4 text-lg font-bold">{p}</p></div></Reveal>)}</div></div></section>}

export function Work({projects=demoProjects}:{projects?:Project[]}){return <section id="work" className="px-5 py-24"><div className="mx-auto max-w-7xl"><Reveal><p className="text-sm uppercase tracking-[.35em] text-amber-200">Case studies</p><h2 className="mt-4 max-w-4xl text-4xl font-black tracking-tight md:text-6xl">Portfolio that looks like real business proof, not random cards.</h2></Reveal><div className="mt-12 grid gap-6 md:grid-cols-3">{projects.map((p,i)=><Reveal delay={i*.05} key={projectSlug(p)}><Link href={`/portfolio/${projectSlug(p)}`} className="group block"><TiltCard className="glass-warm overflow-hidden rounded-[2rem]"><div className="relative h-60 overflow-hidden bg-[radial-gradient(circle_at_20%_20%,rgba(246,200,95,.55),transparent_32%),radial-gradient(circle_at_70%_40%,rgba(255,107,156,.45),transparent_30%),radial-gradient(circle_at_50%_100%,rgba(139,92,246,.55),transparent_34%)]" style={p.image_url?{backgroundImage:`linear-gradient(rgba(18,13,31,.1),rgba(18,13,31,.45)),url(${p.image_url})`,backgroundSize:'cover',backgroundPosition:'center'}:undefined}><div className="absolute inset-5 rounded-[1.5rem] border border-white/15 bg-white/[.04] backdrop-blur-[2px] transition group-hover:scale-[1.03]"/><span className="absolute left-5 top-5 rounded-full bg-[#120d1f]/60 px-3 py-1 text-sm text-amber-100">{p.industry}</span></div><div className="p-7"><h3 className="text-2xl font-black group-hover:text-amber-200">{p.title}</h3><p className="mt-3 text-amber-50/60">{p.summary}</p><p className="mt-5 text-sm font-semibold text-emerald-200">{p.results}</p></div></TiltCard></Link></Reveal>)}</div></div></section>}

export function Comparison(){const rows=[['Template-looking website','Luxury custom visual system'],['Only contact form','Lead CRM + admin pipeline'],['No follow-up','Email alerts + client confirmation'],['Static content','Admin CRUD for blog, pricing, work'],['Generic colors','Memorable gold, rose, violet palette']];return <section className="px-5 py-24"><div className="mx-auto max-w-7xl"><Reveal><h2 className="max-w-4xl text-4xl font-black tracking-tight md:text-6xl">The goal is not just beautiful design. The goal is credibility + conversion.</h2></Reveal><div className="mt-12 overflow-hidden rounded-[2rem] border border-amber-200/15 bg-white/[.04]"><table className="w-full text-left"><thead className="bg-amber-100/10 text-amber-100"><tr><th className="p-5">Before</th><th className="p-5">After NexusNova</th></tr></thead><tbody>{rows.map(([a,b])=><tr className="border-t border-white/10" key={a}><td className="p-5 text-white/42">{a}</td><td className="p-5 font-bold text-amber-100">{b}</td></tr>)}</tbody></table></div></div></section>}

export function Process(){const steps=[['Discover','We define offer, target customer, pages, features, and conversion goals.'],['Design','We craft the premium visual system, sections, mobile UX, and interaction flow.'],['Build','We develop frontend, backend, admin dashboard, database, and email automation.'],['Launch','We deploy on Vercel, connect domain, check SEO, and guide your updates.']];return <section className="px-5 py-24"><div className="mx-auto max-w-7xl"><Reveal><p className="text-sm uppercase tracking-[.35em] text-rose-200">Process</p><h2 className="mt-4 text-4xl font-black tracking-tight md:text-6xl">A clear delivery system clients can trust.</h2></Reveal><div className="mt-12 grid gap-4 md:grid-cols-4">{steps.map(([s,d],i)=><Reveal delay={i*.06} key={s}><div className="glass rounded-3xl p-7"><p className="text-sm text-amber-200/65">0{i+1}</p><h3 className="mt-4 text-2xl font-black">{s}</h3><p className="mt-3 text-amber-50/58">{d}</p></div></Reveal>)}</div></div></section>}

export function TechStack(){const stack=['Next.js','TypeScript','Tailwind CSS','Framer Motion','Supabase','Clerk','Resend','Vercel'];return <section className="px-5 py-24"><div className="mx-auto max-w-7xl"><Reveal><p className="text-sm uppercase tracking-[.35em] text-cyan-200">Production stack</p><h2 className="mt-4 text-4xl font-black tracking-tight md:text-6xl">Fast, secure, scalable, and easy to manage.</h2></Reveal><div className="mt-12 flex flex-wrap gap-3">{stack.map((x,i)=><Reveal delay={i*.03} key={x}><span className="rounded-full border border-amber-200/15 bg-amber-100/8 px-5 py-3 text-amber-50/72">{x}</span></Reveal>)}</div></div></section>}

export function Pricing({plans=pricing}:{plans?:Plan[]}){return <section id="pricing" className="px-5 py-24"><div className="mx-auto max-w-7xl"><Reveal><p className="text-sm uppercase tracking-[.35em] text-amber-200">Pricing</p><h2 className="mt-4 text-4xl font-black tracking-tight md:text-6xl">Transparent packages with premium positioning.</h2></Reveal><div className="mt-12 grid gap-6 md:grid-cols-3">{plans.map((p,i)=>{const price=typeof p.price==='number'?(p.price===0?'Custom':`₹${p.price.toLocaleString('en-IN')}`):p.price;return <Reveal delay={i*.05} key={p.name}><TiltCard className={`glass rounded-[2rem] p-8 ${p.popular?'ring-2 ring-amber-300/60':''}`}>{p.popular&&<span className="rounded-full bg-gradient-to-r from-amber-300 to-rose-400 px-3 py-1 text-sm font-bold text-[#160d20]">Most Popular</span>}<h3 className="mt-5 text-2xl font-black">{p.name}</h3><p className="mt-4 text-5xl font-black text-gradient">{price}</p><p className="mt-3 text-amber-50/60">{p.desc||p.description}</p><ul className="mt-7 space-y-3">{(p.features||[]).map(f=><li className="flex gap-2 text-amber-50/76" key={f}><Check className="shrink-0 text-emerald-300" size={18}/>{f}</li>)}</ul><Link className="btn-lux mt-8 block px-5 py-3 text-center" href="/contact">Get Started</Link></TiltCard></Reveal>})}</div></div></section>}

export function Testimonials({testimonials=[]}:{testimonials?:Testimonial[]}){const fallback=[{name:'Demo Cafe Brand',role:'Restaurant growth concept',company:'NexusNova Demo',quote:'The layout makes the business feel premium and sends customers directly to WhatsApp and booking actions.'},{name:'Clinic Website Concept',role:'Healthcare landing page',company:'NexusNova Demo',quote:'The structure explains services clearly, builds trust, and captures inquiries without confusing visitors.'},{name:'Real Estate Concept',role:'Builder portfolio system',company:'NexusNova Demo',quote:'The case study style makes projects feel credible with visuals, results, and clear contact flow.'}];const list=testimonials.length?testimonials:fallback;return <section className="px-5 py-24"><div className="mx-auto max-w-7xl"><Reveal><p className="text-sm uppercase tracking-[.35em] text-rose-200">Trust signals</p><h2 className="mt-4 text-4xl font-black tracking-tight md:text-6xl">Designed to make visitors feel confidence immediately.</h2></Reveal><div className="mt-12 grid gap-5 md:grid-cols-3">{list.map((t,i)=><Reveal delay={i*.05} key={`${t.name}-${i}`}><div className="glass-warm rounded-[2rem] p-7"><div className="mb-5 flex gap-1 text-amber-300">{Array.from({length:5}).map((_,i)=><Star key={i} size={16} fill="currentColor"/>)}</div><p className="text-amber-50/76">“{t.quote}”</p><p className="mt-6 font-black">{t.name}</p><p className="text-sm text-amber-50/45">{[t.role,t.company].filter(Boolean).join(' • ')}</p></div></Reveal>)}</div></div></section>}

export function FAQ(){return <section className="px-5 py-24"><div className="mx-auto max-w-4xl"><Reveal><p className="text-sm uppercase tracking-[.35em] text-amber-200">FAQ</p><h2 className="mt-4 text-4xl font-black tracking-tight md:text-6xl">Questions clients ask before starting.</h2></Reveal><div className="mt-10 space-y-4">{faqs.map(([q,a])=><Reveal key={q}><details className="glass rounded-3xl p-6"><summary className="cursor-pointer text-lg font-bold">{q}</summary><p className="mt-4 text-amber-50/62">{a}</p></details></Reveal>)}</div></div></section>}

export function FinalCTA(){return <section className="px-5 py-28"><div className="lux-bg noise relative mx-auto max-w-7xl overflow-hidden rounded-[2.5rem] border border-amber-200/15 p-10 text-center shadow-2xl md:p-20"><div className="orb left-10 top-10 h-72 w-72 bg-amber-300/30"/><Reveal><h2 className="mx-auto max-w-4xl text-4xl font-black tracking-tight md:text-7xl">Make your business look expensive, trusted, and ready for growth.</h2><p className="mx-auto mt-6 max-w-2xl text-amber-50/65">Book a free strategy call and get a clear website + automation roadmap for your business.</p><div className="mt-9 flex flex-col justify-center gap-4 sm:flex-row"><Link className="btn-lux px-8 py-4" href="/contact">Book Free Call</Link><Link className="rounded-full border border-amber-200/20 px-8 py-4 font-bold text-amber-50" href="/portfolio">View Case Studies</Link></div></Reveal></div></section>}

export function WhatsApp(){const n=process.env.NEXT_PUBLIC_WHATSAPP_NUMBER||'917558541331';return <a href={`https://wa.me/${n}`} className="fixed bottom-5 right-5 z-50 flex items-center gap-2 rounded-full bg-gradient-to-r from-emerald-400 to-cyan-300 px-5 py-3 font-black text-[#0b2018] shadow-2xl shadow-emerald-400/20"><MessageCircle size={18}/> WhatsApp</a>}
